services:
  mongodb:
    image: mongo:latest
    container_name: prova-agil-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hackathon2025
      MONGO_INITDB_DATABASE: hackathon

volumes:
  mongo-data:
